### ISSUE TITLE
how do I configure datadog host and port at runtime

### ISSUE THREAD

**Issue by davehorton** [garrettsickles/DogFood#15]
Finding it strange that you only show an example of how to compile in the datadog host and address.  I need this to be configurable at runtime

**Comment by garrettsickles** [comment]
That is an interesting consideration. I will look into this. When building this I never found this requirement because the DogStatsD agent is usually started on a static port on the localhost

**Comment by ziliang-nuro** [comment]
@garrettsickles this is particular useful in containerize environment, as as assign private IPs to containers, and client/agent usually are in different container that they communicate over private network.

Given the popularity of containers, I imagine this would be quite useful.

**Comment by garrettsickles** [comment]
Discussion in https://github.com/garrettsickles/DogFood/issues/18
